var songs = [
  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/266528033&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ojaymctrippingparks" title="Mr.O" target="_blank" style="color: #cccccc; text-decoration: none;">Mr.O</a> · <a href="https://soundcloud.com/ojaymctrippingparks/vengaboys-boom-boom-boom-boom-bootleg" title="Vengaboys - Boom - Boom - Boom - Boom (Bootleg)." target="_blank" style="color: #cccccc; text-decoration: none;">Vengaboys - Boom - Boom - Boom - Boom (Bootleg).</a></div>',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/844936537&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/sebseb122" title="SEBii💫" target="_blank" style="color: #cccccc; text-decoration: none;">SEBii💫</a> · <a href="https://soundcloud.com/sebseb122/merrygo" title="SEBii X dolly - merryGO [p. ggedgar + hakeon]" target="_blank" style="color: #cccccc; text-decoration: none;">SEBii X dolly - merryGO [p. ggedgar + hakeon]</a></div>',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/869126575&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/goreshit" title="goreshit" target="_blank" style="color: #cccccc; text-decoration: none;">goreshit</a> · <a href="https://soundcloud.com/goreshit/please-dont" title="please don&#x27;t." target="_blank" style="color: #cccccc; text-decoration: none;">please don&#x27;t.</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/426787488&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/xtreme2themax" title="djX" target="_blank" style="color: #cccccc; text-decoration: none;">djX</a> · <a href="https://soundcloud.com/xtreme2themax/daft-punk-digital-love-djx-flip" title="DAFT PUNK - DIGITAL LOVE (djX FLIP)" target="_blank" style="color: #cccccc; text-decoration: none;">DAFT PUNK - DIGITAL LOVE (djX FLIP)</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/601056813&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/djfingerblast666" title="DJ FINGERBLAST" target="_blank" style="color: #cccccc; text-decoration: none;">DJ FINGERBLAST</a> · <a href="https://soundcloud.com/djfingerblast666/charli-xcx-vroom-vroom-dj-fingerblast-remix" title="CHARLI XCX - VROOM VROOM [DJ FINGERBLAST REMIX]" target="_blank" style="color: #cccccc; text-decoration: none;">CHARLI XCX - VROOM VROOM [DJ FINGERBLAST REMIX]</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/783953278&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/bladee1000" title="BLADEE" target="_blank" style="color: #cccccc; text-decoration: none;">BLADEE</a> · <a href="https://soundcloud.com/bladee1000/wonderland-feat-ecco2k" title="WONDERLAND (feat. Ecco2k)" target="_blank" style="color: #cccccc; text-decoration: none;">WONDERLAND (feat. Ecco2k)</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/878134318&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/alice-gass" title="ALICE GAS" target="_blank" style="color: #cccccc; text-decoration: none;">ALICE GAS</a> · <a href="https://soundcloud.com/alice-gass/dolly-alice-angelus-legroom-prod-dolly-alice" title="dolly + alice + angelus - leg room [prod. dolly + alice]" target="_blank" style="color: #cccccc; text-decoration: none;">dolly + alice + angelus - leg room [prod. dolly + alice]</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/662206103&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/primordial_void" title="Primordial Void" target="_blank" style="color: #cccccc; text-decoration: none;">Primordial Void</a> · <a href="https://soundcloud.com/primordial_void/lockbox-im-a-dj" title="Lockbox - I&#x27;m a DJ" target="_blank" style="color: #cccccc; text-decoration: none;">Lockbox - I&#x27;m a DJ</a></div> ',

  ' <iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/460251186&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ice-underlord" title="ICEUNDERLORD" target="_blank" style="color: #cccccc; text-decoration: none;">ICEUNDERLORD</a> · <a href="https://soundcloud.com/ice-underlord/pretty-boy-swag-yeshomoremix" title="PRETTY BOY SWAG (YES HOMO REMIX)" target="_blank" style="color: #cccccc; text-decoration: none;">PRETTY BOY SWAG (YES HOMO REMIX)</a></div> ',

  ' <iframe width="100%" height="166" src="https://www.youtube.com/embed/GvUzo9Rzdxs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> ',
  ' <iframe width="100%" height="166" src="https://www.youtube.com/embed/v6WGEVg_W_Q" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> ',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/877589293&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/chuckybabyhardcore" title="Chucky Baby" target="_blank" style="color: #cccccc; text-decoration: none;">Chucky Baby</a> · <a href="https://soundcloud.com/chuckybabyhardcore/01-tearz-2-cry-feat-gfoty" title="Tearz ← 2 Cry (feat. GFOTY)" target="_blank" style="color: #cccccc; text-decoration: none;">Tearz ← 2 Cry (feat. GFOTY)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/887285170&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/boredlord" title="Bored Lord" target="_blank" style="color: #cccccc; text-decoration: none;">Bored Lord</a> · <a href="https://soundcloud.com/boredlord/yall-better-quiet-down-off-of-delusional-breaks" title="yall better quiet down (off of &quot;delusional breaks&quot;)" target="_blank" style="color: #cccccc; text-decoration: none;">yall better quiet down (off of &quot;delusional breaks&quot;)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/824602204&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/tall-ceo" title="TALL CEO" target="_blank" style="color: #cccccc; text-decoration: none;">TALL CEO</a> · <a href="https://soundcloud.com/tall-ceo/phantasy-star-online-tall-ceo-hyper-jersey-bootleg" title="deko - PHANTASY STAR ONLINE [TALL CEO BOOTLEG]" target="_blank" style="color: #cccccc; text-decoration: none;">deko - PHANTASY STAR ONLINE [TALL CEO BOOTLEG]</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/864654505&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lilgripguy" title="lil grip" target="_blank" style="color: #cccccc; text-decoration: none;">lil grip</a> · <a href="https://soundcloud.com/lilgripguy/sour-dog-version" title="sour (dog version)" target="_blank" style="color: #cccccc; text-decoration: none;">sour (dog version)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/866045170&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/djmag" title="djmag" target="_blank" style="color: #cccccc; text-decoration: none;">djmag</a> · <a href="https://soundcloud.com/djmag/bastiengoat-slurpee" title="Bastiengoat &#x27;Slurpee&#x27;" target="_blank" style="color: #cccccc; text-decoration: none;">Bastiengoat &#x27;Slurpee&#x27;</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/781216348&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/g0ld3nb0y" title="Golden Boy" target="_blank" style="color: #cccccc; text-decoration: none;">Golden Boy</a> · <a href="https://soundcloud.com/g0ld3nb0y/golden-boy-demo-ready-for-a-beatdown" title="Ruffneck killa" target="_blank" style="color: #cccccc; text-decoration: none;">Ruffneck killa</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/738922033&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/djhimera" title="Himera" target="_blank" style="color: #cccccc; text-decoration: none;">Himera</a> · <a href="https://soundcloud.com/djhimera/voicenote" title="Voicenote" target="_blank" style="color: #cccccc; text-decoration: none;">Voicenote</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/560676762&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/date-sim" title="DATE SIM" target="_blank" style="color: #cccccc; text-decoration: none;">DATE SIM</a> · <a href="https://soundcloud.com/date-sim/dickpic" title="Dick Pic" target="_blank" style="color: #cccccc; text-decoration: none;">Dick Pic</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/722352670&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/alice-gass" title="ALICE GAS" target="_blank" style="color: #cccccc; text-decoration: none;">ALICE GAS</a> · <a href="https://soundcloud.com/alice-gass/ferrari" title="FERRARI" target="_blank" style="color: #cccccc; text-decoration: none;">FERRARI</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/694340236&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ice-underlord" title="ICEUNDERLORD" target="_blank" style="color: #cccccc; text-decoration: none;">ICEUNDERLORD</a> · <a href="https://soundcloud.com/ice-underlord/crack-music" title="CRACK MUSIC" target="_blank" style="color: #cccccc; text-decoration: none;">CRACK MUSIC</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/688330675&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/prophetsofhardcore" title="PROPHETS OF HARDCORE" target="_blank" style="color: #cccccc; text-decoration: none;">PROPHETS OF HARDCORE</a> · <a href="https://soundcloud.com/prophetsofhardcore/prophetic" title="PROPHETIC (SEXYEYES33 &amp; TECHNOPAGAN)" target="_blank" style="color: #cccccc; text-decoration: none;">PROPHETIC (SEXYEYES33 &amp; TECHNOPAGAN)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/398751063&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/codeveronica" title="veronica x" target="_blank" style="color: #cccccc; text-decoration: none;">veronica x</a> · <a href="https://soundcloud.com/codeveronica/fireflies" title="fireflies" target="_blank" style="color: #cccccc; text-decoration: none;">fireflies</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/183863497&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/onikalovesyou" title="σníkα" target="_blank" style="color: #cccccc; text-decoration: none;">σníkα</a> · <a href="https://soundcloud.com/onikalovesyou/i-still-love-you-but" title="I still love you but (tay bootleg)" target="_blank" style="color: #cccccc; text-decoration: none;">I still love you but (tay bootleg)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/593386506&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/bah-bu-rah" title="Bah Bu Rah" target="_blank" style="color: #cccccc; text-decoration: none;">Bah Bu Rah</a> · <a href="https://soundcloud.com/bah-bu-rah/chibi" title="Chibi ♡" target="_blank" style="color: #cccccc; text-decoration: none;">Chibi ♡</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/778079797&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/technopagan420" title="technopagan" target="_blank" style="color: #cccccc; text-decoration: none;">technopagan</a> · <a href="https://soundcloud.com/technopagan420/gamecube-fever-dream-bootleg-euro-mix" title="gamecube fever dream... (bootleg euro mix)" target="_blank" style="color: #cccccc; text-decoration: none;">gamecube fever dream... (bootleg euro mix)</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/883025797&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/angrybirdvevo" title="bye2" target="_blank" style="color: #cccccc; text-decoration: none;">bye2</a> · <a href="https://soundcloud.com/angrybirdvevo/nintendo-ds-soul-injection" title="Nintendo DS Soul Injection" target="_blank" style="color: #cccccc; text-decoration: none;">Nintendo DS Soul Injection</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/748472110&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/dissolve4" title="DJ Kuroneko/DisSolve" target="_blank" style="color: #cccccc; text-decoration: none;">DJ Kuroneko/DisSolve</a> · <a href="https://soundcloud.com/dissolve4/heartless" title="heartless" target="_blank" style="color: #cccccc; text-decoration: none;">heartless</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/878154910&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/puppywuv" title="☆puppy☆" target="_blank" style="color: #cccccc; text-decoration: none;">☆puppy☆</a> · <a href="https://soundcloud.com/puppywuv/wap" title="💦🍑🐱" target="_blank" style="color: #cccccc; text-decoration: none;">💦🍑🐱</a></div>',

  '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/756446608&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/gupimusic" title="gupi" target="_blank" style="color: #cccccc; text-decoration: none;">gupi</a> · <a href="https://soundcloud.com/gupimusic/thos-moser" title="Thos Moser" target="_blank" style="color: #cccccc; text-decoration: none;">Thos Moser</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/573494523&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/kingdoudou" title="King Doudou" target="_blank" style="color: #cccccc; text-decoration: none;">King Doudou</a> · <a href="https://soundcloud.com/kingdoudou/mc-lucy-sento-no-bico-da-glock-king-doudou-remix" title="MC Lucy - Sento no bico da glock (King Doudou Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">MC Lucy - Sento no bico da glock (King Doudou Remix)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/606743094&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/pdamusiq" title="PDA PRODUCTIONS" target="_blank" style="color: #cccccc; text-decoration: none;">PDA PRODUCTIONS</a> · <a href="https://soundcloud.com/pdamusiq/shygirl-beauts-junglist-rmx" title="SHYGIRL — BEAUTS JUNGLIST RMX" target="_blank" style="color: #cccccc; text-decoration: none;">SHYGIRL — BEAUTS JUNGLIST RMX</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/873222679&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/penciler" title="pencil" target="_blank" style="color: #cccccc; text-decoration: none;">pencil</a> · <a href="https://soundcloud.com/penciler/asbnt" title="Asbnt" target="_blank" style="color: #cccccc; text-decoration: none;">Asbnt</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/318156513&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/debbyfriday" title="DEBBY FRIDAY" target="_blank" style="color: #cccccc; text-decoration: none;">DEBBY FRIDAY</a> · <a href="https://soundcloud.com/debbyfriday/hella-guud-debby-friday-bootleg" title="HELLA GUUD (FRIDAY BOOTLEG)" target="_blank" style="color: #cccccc; text-decoration: none;">HELLA GUUD (FRIDAY BOOTLEG)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/854285488&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/100gecs" title="100 gecs" target="_blank" style="color: #cccccc; text-decoration: none;">100 gecs</a> · <a href="https://soundcloud.com/100gecs/hand-crushed-by-a-mallet-remix-feat-fallout-boy-craig-owens-nicole-dollanganger" title="hand crushed by a mallet (Remix) (feat. Fall Out Boy, Craig Owens, Nicole Dollanganger)" target="_blank" style="color: #cccccc; text-decoration: none;">hand crushed by a mallet (Remix) (feat. Fall Out Boy, Craig Owens, Nicole Dollanganger)</a></div>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/9sD4XekDwv0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/411822696&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/rhalp-darren-cabrera" title="Rhalp Darren Cabrera" target="_blank" style="color: #cccccc; text-decoration: none;">Rhalp Darren Cabrera</a> · <a href="https://soundcloud.com/rhalp-darren-cabrera/triggerhappy-extended" title="P*Light - TRIGGER★HAPPY(Hommarju Remix)  Extended" target="_blank" style="color: #cccccc; text-decoration: none;">P*Light - TRIGGER★HAPPY(Hommarju Remix)  Extended</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/875188348&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/rico_nasty" title="RICO NASTY" target="_blank" style="color: #cccccc; text-decoration: none;">RICO NASTY</a> · <a href="https://soundcloud.com/rico_nasty/iphone" title="iPhone" target="_blank" style="color: #cccccc; text-decoration: none;">iPhone</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/868885156&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/idk123idk" title="healboi//bedside" target="_blank" style="color: #cccccc; text-decoration: none;">healboi//bedside</a> · <a href="https://soundcloud.com/idk123idk/yeah-yeah-yeahs-maps-healboi" title="yeah yeah yeahs - maps (healboi bediside&#x27;s i love you peach remix)" target="_blank" style="color: #cccccc; text-decoration: none;">yeah yeah yeahs - maps (healboi bediside&#x27;s i love you peach remix)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/616579458&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/djpewpewpew" title="DJ PEWPEWPEW" target="_blank" style="color: #cccccc; text-decoration: none;">DJ PEWPEWPEW</a> · <a href="https://soundcloud.com/djpewpewpew/tokyo-twist" title="TOKYO TWIST (FREE DOWNLOAD)" target="_blank" style="color: #cccccc; text-decoration: none;">TOKYO TWIST (FREE DOWNLOAD)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/738148960&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/sonidochiquito" title="Sonido Chiquito" target="_blank" style="color: #cccccc; text-decoration: none;">Sonido Chiquito</a> · <a href="https://soundcloud.com/sonidochiquito/summer-fast-version" title="my own summer (SEND IT) x.x" target="_blank" style="color: #cccccc; text-decoration: none;">my own summer (SEND IT) x.x</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/563369163&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/4nzu2" title="4nzu" target="_blank" style="color: #cccccc; text-decoration: none;">4nzu</a> · <a href="https://soundcloud.com/4nzu2/dearest" title="DEAREST" target="_blank" style="color: #cccccc; text-decoration: none;">DEAREST</a></div>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/eO4BdxdXEZI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/opANoiNZ-t8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/xL21Z3da1h8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/EjB84IBomXs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/qN8hQWH-pAg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/375721721&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/kfour9" title="K9999" target="_blank" style="color: #cccccc; text-decoration: none;">K9999</a> · <a href="https://soundcloud.com/kfour9/skin-k9999-edit" title="bladee - Skin (K9999 edit)" target="_blank" style="color: #cccccc; text-decoration: none;">bladee - Skin (K9999 edit)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/460939881&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/moerbeck" title="Mørbeck / Low Life Club" target="_blank" style="color: #cccccc; text-decoration: none;">Mørbeck / Low Life Club</a> · <a href="https://soundcloud.com/moerbeck/moerbeck-brain-hack-golden-circle-001" title="Moerbeck - Brain Hack (Golden Circle 001 out now)" target="_blank" style="color: #cccccc; text-decoration: none;">Moerbeck - Brain Hack (Golden Circle 001 out now)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/672935486&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/boredlord" title="Bored Lord" target="_blank" style="color: #cccccc; text-decoration: none;">Bored Lord</a> · <a href="https://soundcloud.com/boredlord/duality-off-of-nu-metal-toolz-vol-2" title="dUaLiTy (off of &quot;Nu Metal Toolz Vol. 2&quot;)" target="_blank" style="color: #cccccc; text-decoration: none;">dUaLiTy (off of &quot;Nu Metal Toolz Vol. 2&quot;)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/726018280&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/goreshit" title="goreshit" target="_blank" style="color: #cccccc; text-decoration: none;">goreshit</a> · <a href="https://soundcloud.com/goreshit/ap2demo1" title="ap2demo1" target="_blank" style="color: #cccccc; text-decoration: none;">ap2demo1</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/756292972&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/caramellagirls-music" title="Caramella Girls" target="_blank" style="color: #cccccc; text-decoration: none;">Caramella Girls</a> · <a href="https://soundcloud.com/caramellagirls-music/caramelldansen" title="Caramelldansen" target="_blank" style="color: #cccccc; text-decoration: none;">Caramelldansen</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/676090043&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/medievalslimes" title="𝔐𝔢𝔡𝔦𝔢𝔳𝔞𝔩 𝔖𝔩𝔦𝔪𝔢𝔰" target="_blank" style="color: #cccccc; text-decoration: none;">𝔐𝔢𝔡𝔦𝔢𝔳𝔞𝔩 𝔖𝔩𝔦𝔪𝔢𝔰</a> · <a href="https://soundcloud.com/medievalslimes/partytiime-single" title="Partytiime" target="_blank" style="color: #cccccc; text-decoration: none;">Partytiime</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/762885793&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/160club" title="160 CLUB" target="_blank" style="color: #cccccc; text-decoration: none;">160 CLUB</a> · <a href="https://soundcloud.com/160club/s-045" title="THE CHAINSMOKERS - CLOSER (MURDER CLUB BOOTLEG)" target="_blank" style="color: #cccccc; text-decoration: none;">THE CHAINSMOKERS - CLOSER (MURDER CLUB BOOTLEG)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/879903325&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/faded-boo" title="Faded Boo" target="_blank" style="color: #cccccc; text-decoration: none;">Faded Boo</a> · <a href="https://soundcloud.com/faded-boo/they-call-me-sonic-1" title="They Call Me Sonic" target="_blank" style="color: #cccccc; text-decoration: none;">They Call Me Sonic</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/458065932&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/tvddj" title="TVDDJ✪" target="_blank" style="color: #cccccc; text-decoration: none;">TVDDJ✪</a> · <a href="https://soundcloud.com/tvddj/flo-rida-low-low-dj-tvd-remix" title="Flo Rida - Low Low - DJ TVD Remix" target="_blank" style="color: #cccccc; text-decoration: none;">Flo Rida - Low Low - DJ TVD Remix</a></div>',

'<iframe width="100%" height="166" src="https://www.youtube.com/embed/VAaA1V0IFLE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/593228115&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-602927604" title="Mind Flayer" target="_blank" style="color: #cccccc; text-decoration: none;">Mind Flayer</a> · <a href="https://soundcloud.com/user-602927604/super-mind-flayer-world" title="Super Mind Flayer World (Nitti Gritti X Super Mario World)" target="_blank" style="color: #cccccc; text-decoration: none;">Super Mind Flayer World (Nitti Gritti X Super Mario World)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/236091913&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/scottneeson1" title="Scott Neeson (SSD)" target="_blank" style="color: #cccccc; text-decoration: none;">Scott Neeson (SSD)</a> · <a href="https://soundcloud.com/scottneeson1/wonderwall" title="Wonderwall" target="_blank" style="color: #cccccc; text-decoration: none;">Wonderwall</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/819368212&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-574612227" title="jahy sama" target="_blank" style="color: #cccccc; text-decoration: none;">jahy sama</a> · <a href="https://soundcloud.com/user-574612227/sega-bodega-dorian-electra" title="Sega Bodega &amp; Dorian Electra - Teenage Dirtbag (Cover)" target="_blank" style="color: #cccccc; text-decoration: none;">Sega Bodega &amp; Dorian Electra - Teenage Dirtbag (Cover)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/234959823&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mall-music-inc" title="MALL MUSIC INC." target="_blank" style="color: #cccccc; text-decoration: none;">MALL MUSIC INC.</a> · <a href="https://soundcloud.com/mall-music-inc/dj-mastercard-lethal-feat-dj-paypal" title="DJ Mastercard - Lethal Feat. DJ Paypal" target="_blank" style="color: #cccccc; text-decoration: none;">DJ Mastercard - Lethal Feat. DJ Paypal</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/596027622&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/iamquestionmarc" title="quest?onmarc" target="_blank" style="color: #cccccc; text-decoration: none;">quest?onmarc</a> · <a href="https://soundcloud.com/iamquestionmarc/ha-ha-ha-questonmarc-bootleg-smf" title="HaHaHA (quest?onmarc Bootleg) - SMF" target="_blank" style="color: #cccccc; text-decoration: none;">HaHaHA (quest?onmarc Bootleg) - SMF</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/750366730&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/vengaboys-official" title="Vengaboys" target="_blank" style="color: #cccccc; text-decoration: none;">Vengaboys</a> · <a href="https://soundcloud.com/vengaboys-official/we-like-to-party-the-2" title="We like to Party! (The Vengabus) (Jason Nevins RMX)" target="_blank" style="color: #cccccc; text-decoration: none;">We like to Party! (The Vengabus) (Jason Nevins RMX)</a></div>',

'<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/17910437&color=%23eb00ff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/dj-trapp-1" title="DJ RaDio KillA" target="_blank" style="color: #cccccc; text-decoration: none;">DJ RaDio KillA</a> · <a href="https://soundcloud.com/dj-trapp-1/youre-a-jerk-jersey-club-mix" title="You&#x27;re a jerk jersey club mix" target="_blank" style="color: #cccccc; text-decoration: none;">You&#x27;re a jerk jersey club mix</a></div>',

]
// document.getElementById("yourelement").innerHTML = answer[0];

function newSong() {
  var randomNumber = Math.floor(Math.random() * (songs.length));
  document.getElementById('songDisplay').innerHTML = songs[randomNumber];
}
